### ISSUE TITLE
AttributeError: 'module' object has no attribute 'VariantRecord'

### ISSUE THREAD

**Issue by greekkey** [dmiller903/CompoundHetVIP#3]
HI,  @dmiller903
I continued from step 6. The following steps 7~10 were done. Now I encountered a new error in Step 11 using GEMINI. 
Here is my command (I changed path and --num_cores according to my computer)

    mkdir /media/ngs/BAM5T/AnnovarDB/reference/gemini_data

    docker run -d -v /mnt/nas/program_test/CompoundHetVIP/example:/proj \
    -v /media/ngs/BAM5T/AnnovarDB/reference/gemini_data:/usr/local/share/gemini/gemini_data \
    -w /proj -t dmill903/compound-het-vip:1.0 \
    python3 /gemini_load.py \
    giab/giab_annotated.vcf \
    giab/giab.db \
    --fam_file giab/giab_trio.fam \
    --num_cores 4 \
    > /mnt/nas/program_test/CompoundHetVIP/example/giab/gemini_load.out

    CONTAINERID=$(cat /mnt/nas/program_test/CompoundHetVIP/example/giab/gemini_load.out)
    docker logs -f ${CONTAINERID}

**Comment by greekkey** [comment]
Here is the error information: 

/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
config = yaml.load(in_handle)
CADD scores are being loaded (to skip use:--skip-cadd).

GERP per bp is not being loaded because the annotation file could not be found.
Run `gemini update --dataonly --extra gerp_bp` to install the annotation file.

Loading with existing bgzip (/proj/giab/giab_annotated.vcf.gz) version of /proj/giab/giab_annotated.vcf.
Loading 3150761 variants.
Breaking /proj/giab/giab_annotated.vcf.gz into 4 chunks.
Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
gemini_load_chunk.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 916, in load
gemini_loader.populate_from_vcf()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 223, in populate_from_vcf
(variant, variant_impacts) = self._prepare_variation(var, anno_keys)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 406, in _prepare_variation
rs_ids = annotations.get_dbsnp_info(var)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 664, in get_dbsnp_info
for hit in annotations_in_vcf(var, "dbsnp", "vcf", "grch37"):
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 422, in annotations_in_vcf
if isinstance(h, (cyvcf2.Variant, pysam.VariantRecord)):
AttributeError: 'module' object has no attribute 'VariantRecord'
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
gemini_load_chunk.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 916, in load
gemini_loader.populate_from_vcf()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 223, in populate_from_vcf
(variant, variant_impacts) = self._prepare_variation(var, anno_keys)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 406, in _prepare_variation
rs_ids = annotations.get_dbsnp_info(var)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 664, in get_dbsnp_info
for hit in annotations_in_vcf(var, "dbsnp", "vcf", "grch37"):
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 422, in annotations_in_vcf
if isinstance(h, (cyvcf2.Variant, pysam.VariantRecord)):
AttributeError: 'module' object has no attribute 'VariantRecord'
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
gemini_load_chunk.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 916, in load
gemini_loader.populate_from_vcf()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 223, in populate_from_vcf
(variant, variant_impacts) = self._prepare_variation(var, anno_keys)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 406, in _prepare_variation
rs_ids = annotations.get_dbsnp_info(var)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 664, in get_dbsnp_info
for hit in annotations_in_vcf(var, "dbsnp", "vcf", "grch37"):
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 422, in annotations_in_vcf
if isinstance(h, (cyvcf2.Variant, pysam.VariantRecord)):
AttributeError: 'module' object has no attribute 'VariantRecord'
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 311, in loadchunk_fn
gemini_load_chunk.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 916, in load
gemini_loader.populate_from_vcf()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 223, in populate_from_vcf
(variant, variant_impacts) = self._prepare_variation(var, anno_keys)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 406, in _prepare_variation
rs_ids = annotations.get_dbsnp_info(var)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 664, in get_dbsnp_info
for hit in annotations_in_vcf(var, "dbsnp", "vcf", "grch37"):
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 422, in annotations_in_vcf
if isinstance(h, (cyvcf2.Variant, pysam.VariantRecord)):
AttributeError: 'module' object has no attribute 'VariantRecord'
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
gemini_load.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 49, in load
load_multicore(args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 93, in load_multicore
chunks = load_chunks_multicore(grabix_file, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 264, in load_chunks_multicore
wait_until_finished(procs)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 359, in wait_until_finished
raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load

**********************************************************************
Done. Time elapsed: 0.26 minutes (0.0 hours)
**********************************************************************


Best regards!
Jacob

**Comment by dmiller903** [comment]
Hey Jacob,

Sorry this took me a little longer to get to with the holiday. It looks like GEMINI started using a different version of pysam and it broke the GEMINI load step. So the last time I built the docker image, it must have used the different version of pysam that broke the GEMINI load step. I updated the version of pysam in the docker image and pushed it to Docker Hub. So pull the latest version (1.1) form there and use it instead. It should solve the issue. 

`docker pull dmill903/compound-het-vip:1.1`

Best,

Dustin

**Comment by greekkey** [comment]
Hi, Dustin
    I'm just back to work from holiday. Thank you very much for updating the software. I downloaded the new version. It is working now. I'll let you know the result when it finished.
    Wish You a Happy New Year! 
Jacob

**Comment by greekkey** [comment]
Hi, Dustin
The new version worked on GEMINI but ended with an sqlite3.OperationalError

Here is my command: 
`docker run -d -v /mnt/nas/program_test/CompoundHetVIP/example:/proj \`
 ` -v /media/ngs/BAM5T/AnnovarDB/reference/gemini_data:/usr/local/share/gemini/gemini_data \`
  `-w /proj -t dmill903/compound-het-vip:1.1 \`
 ` python3 /gemini_load.py \`
  `giab/giab_annotated.vcf \`
  `giab/giab.db \`
 ` --fam_file giab/giab_trio.fam \`
  `--num_cores 4 \`
  `> /mnt/nas/program_test/CompoundHetVIP/example/giab/gemini_load.out`

`CONTAINERID=$(cat /mnt/nas/program_test/CompoundHetVIP/example/giab/gemini_load.out)`
`docker logs -f ${CONTAINERID}`

**Comment by greekkey** [comment]
Here is the log on screen: 

/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
CADD scores are being loaded (to skip use:--skip-cadd).

GERP per bp is not being loaded because the annotation file could not be found.
    Run `gemini update --dataonly --extra gerp_bp` to install the annotation file.

Loading with existing bgzip (/proj/giab/giab_annotated.vcf.gz) version of /proj/giab/giab_annotated.vcf.
Loading 3150761 variants.
Breaking /proj/giab/giab_annotated.vcf.gz into 4 chunks.
Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
pid 30: 9999 variants processed.
pid 24: 9999 variants processed.
pid 21: 9999 variants processed.
....................................................................................................
pid 27: 779999 variants processed.
pid 27: 787690 variants processed.
Done loading 3150761 variants in 4 chunks.
2022-01-04 11:19:10 merging 4 chunks.
2022-01-04 11:22:00 merging 2 chunks.
2022-01-04 11:22:37 merged to final database....
2022-01-04 11:22:37 moved.
storing version, header, etc.
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1249, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 52, in load
    finish(args, l)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 63, in finish
    loader.store_resources()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 156, in store_resources
    database.insert_resources(self.c, self.metadata, annotations.get_resources(self.args))
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/database.py", line 528, in insert_resources
    session.commit()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 507, in commit
    t[1].commit()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1736, in commit
    self._do_commit()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1767, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 757, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 755, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 541, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)

**********************************************************************
Done. Time elapsed: 209.96 minutes (3.5 hours)
**********************************************************************

**Comment by greekkey** [comment]
Thank you in advance!
Jacob

**Comment by dmiller903** [comment]
Looks like SQLite doesn’t play well with NFS. See this thread https://github.com/arq5x/gemini/issues/771

Do you have enough space to save the output locally?

**Comment by greekkey** [comment]
I have 359G free space in the partition of /home , 459G for the partition of /usr and 22G in the partition of /  .  I hope it will be enough. I am now downloading the files from NAS to /home and I will do again on local disk.

**Comment by greekkey** [comment]
Hi @dmiller903 You are right, I think this time the program ended without an error. Thank you!

Loading with existing bgzip (/proj/giab/giab_annotated.vcf.gz) version of /proj/giab/giab_annotated.vcf.
Loading 3150761 variants.
Breaking /proj/giab/giab_annotated.vcf.gz into 4 chunks.
Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/config.py:61: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(in_handle)
pid 30: 9999 variants processed.
pid 24: 9999 variants processed.
pid 21: 9999 variants processed.
pid 27: 9999 variants processed.
....................................................................................................
pid 21: 787690 variants processed.
pid 27: 779999 variants processed.
pid 27: 787690 variants processed.
Done loading 3150761 variants in 4 chunks.
2022-01-05 07:54:50 merging 4 chunks.
2022-01-05 07:57:38 merging 2 chunks.
2022-01-05 07:58:18 merged to final database....
2022-01-05 07:58:18 moved.
storing version, header, etc.
storing gene-detailed
storing gene-summary
updating gene-table
building indices

**********************************************************************
Done. Time elapsed: 215.02 minutes (3.58 hours)
**********************************************************************

**Comment by greekkey** [comment]
Hi @dmiller903 
I finished the following steps (those steps were very fast). 

[Here](https://drive.google.com/drive/folders/1ZE16rIaXJG2jnX_BeC8kT-gGi0mPeHGZ?usp=sharing) is my final result. 

Are they correct?
Jacob

**Comment by dmiller903** [comment]
Yes, that looks correct. There are only 2 CH variants when ran with the default parameters and no de novo variants for the GIAB data. For CH variants you can play around with the --maf, --cadd, and --upper_bound arguments to identify more CH variants. Under default parameters both maf and cadd are set to 0.01 which is pretty strict and cadd is set to 15. That means both variants in a CH variant pair have to have a maf less than or equal to 0.01 and a cadd greater than or equal to 15. For example, If you adjust maf to 0.05 and upper_bound to 0.30, this will require that one of the variants in the CH pair be less or equal to 0.05 and the other be less than or equal to 0.30 (if you leave cadd at default then both variants will also have to have a cadd greater than or equal to 15). Our logic for why you may want to do this is found here in the methods section where we talk about identifying CH variants: https://www.frontiersin.org/articles/10.3389/fgene.2021.640242/full

Also, in that paper you'll see that "potentially damaging" CH variants are pretty rare (based on the restrictions we set for how we define "potentially damaging").

**Comment by greekkey** [comment]
@dmiller903 Hi! Thanks for confirming the results and explaining in detail. Then I will start using it on my own data. If I have other questions or problems, I will post them in new issues. 
Best regards!
Jacob
